workspace:
  base: /drone
  path: .

pipeline:
  build:
    image: plugins/docker
    commands:
      - echo "Hello world"
      - pwd
    #镜像名。
    repo: xuguoliang1995/drone
    dockerfile: ./Dockerfile

#  publish:
#      image: plugins/docker
#      registry: https://index.docker.io/v1/ # 仓库
#      repo: bysir/golang_base # docker仓库地址
#      # mirror: https://docker.mirrors.ustc.edu.cn
#      # 需要使用drone cli添加secrets: http://docs.drone.io/manage-secrets/
#      secrets: [ xuguoliang, "0123qw456xuguo?" ]
#      tags:
#        - latest
##
#  deploy:
#      image: appleboy/drone-ssh
#      host: 47.94.204.137
#      username: root
#      port: 22
#      secrets: [ ssh_key ]
#      script:
#        - cd /root/app
#        - docker-compose pull bysir/golang_base
#        - docker-compose up
