workspace:
  base: /tmp
  path: /drone/src/github.com/xuguoliang1995/drone
# 备注
pipeline:
  build:
    image: ubuntu:16.04
    commands:
      - pwd
      - echo "start"
    dockerfile: ./Dockerfile

  publish:
    image: plugins/docker
    registry: https://hub.docker.com/r/xuguoliang1995/drone/ # 仓库
    repo: xuguoliang1995/drone # docker仓库地址
    secrets: [ xuguoliang1995, "0123qw456xuguo?" ]
    tags:
      - latest

#  deploy:
#      image: appleboy/drone-ssh
#      host: 47.94.204.137
#      username: root
#      port: 22
#      secrets: [ ssh_key ]
#      script:
#        - cd /root/app
#        - docker-compose pull bysir/golang_base
#        - docker-compose up

#  notify:
#    image: drillster/drone-email
#    host: smtp.some-server.com
#    username: foo
#    password: bar
#    from: drone@your-domain.com
#+   attachment: build-result.xml
#    when:
#      status: [ changed, failure ]

