pipeline:
  build:
    image: ubuntu:16.04
    commands:
      - apt-get update
      - pwd
      - echo "start"
  
  deploy:
    image: appleboy/drone-ssh
    host: xuguoliang.cc
    username: root
    password: 0123qw456xuguo?    
    port: 22
      #drone为私钥 这儿为公钥。
     # secrets: [ /root/.ssh/id_rsa ]
    script:
       - pwd
       - docker pull xuguoliang1995/flask
       - docker run xuguoliang1995/flask
  # 插件会干两件事情, 1. upgrade 2. finish upgrade
  # 注意如果这个服务不在Active状态就不能正常升级, 需要登录rancher修改状态, 正常情况下不会发生这个错误.
  rancher:
    image: peloton/drone-rancher
    url: xuguoliang.cc:5000
    #access_key: [ /root/.ssh/id_rsa.pub ]
    #secret_key: [ /root/.ssh/id_rsa ]
    service: xuguoliang1995/flask
    # 为了使rancher能拉取到私有镜像, 需要在rancher控制面板"基础架构->镜像库"添加这个私有镜像库
    docker_image: xuguoliang1995/flask
    start_first: true # 先启动新服务, 后停止原服务. 如果为false则先关闭原服务再启动
    confirm: true
    timeout: 200 # 如果rancher没在这个时间内升级成功则报错, 服务大小等差异会导致升级时间不一样, 可根据自己业务修改超时时间.
    when:
      branch: develop

  notify:
    image: drillster/drone-email
    host: pop.163.com
    username: 18722511536@163.com
    password: 0123qw456xuguo
    from: 18722511536@163.com
#+   attachment: build-result.xml
    when:
      status: [ changed, failure ]

