pipeline:
  build:
    image: ubuntu:16.04
    commands:
      - apt-get update
      - pwd
      - echo "start"
  
  publish:
    image: plugins/docker
    #registry: https://hub.docker.com/
    repo: xuguoliang1995/flask
    dockerfile: ./Dockerfile
    #username: xuguoliang1995
   # password: 0123qw456xuguo
    secrets: [ xuguoliang1995, 0123qw456xuguo ]
    tags: latest
  deploy:
      image: appleboy/drone-ssh
      host: 120.78.93.5
      username: root
      password: 0123qw456xuguo?    
      port: 22
      #secrets: [ ssh_password ]
      script:
        - pwd
        - docker push xuguoliang1995/flask
        - docker start xuguoliang1995/flask

  notify:
    image: xuguoliang1995/drone
    host: 122
    username: foo
    password: bar
    from: drone@your-domain.com
#+   attachment: build-result.xml
#    when:
#      status: [ changed, failure ]

