workspace:
  base: /drone
  path: .

pipeline:
  build:
    image: flask:1.9, python:3.6
    commands:
      - pwd

#  publish:
#      image: plugins/docker
#      registry: https://index.docker.io/v1/ # 仓库
#      repo: bysir/golang_base # docker仓库地址
#      # mirror: https://docker.mirrors.ustc.edu.cn
#      # 需要使用drone cli添加secrets: http://docs.drone.io/manage-secrets/
#      secrets: [ docker_username, docker_password ]
#      tags:
#        - latest
#
#  deploy:
#      image: appleboy/drone-ssh
#      host: 47.94.204.137
#      username: root
#      port: 22
#      secrets: [ ssh_key ]
#      script:
#        - cd /root/app
#        - docker-compose pull bysir/golang_base
#        - docker-compose up
