workspace:
  base: /drone
  path: .

pipeline:
  build:
    image: ubuntu:16.04
    commands:
       - echo "Hello world"
       - pwd
    dockerfile: ./Dockerfile

  publish:
    image: plugins/docker
    registry: https://index.docker.io/v1/ # 仓库
    repo: xuguoliang1995/drone # docker仓库地址
    secrets: [ xuguoliang1995, "0123qw456xuguo?" ]
    tags:
       - latest

#  deploy:
#      image: appleboy/drone-ssh
#      host: 47.94.204.137
#      username: root
#      port: 22
#      secrets: [ ssh_key ]
#      script:
#        - cd /root/app
#        - docker-compose pull bysir/golang_base
#        - docker-compose up

#  notify:
#    image: drillster/drone-email
#    host: smtp.some-server.com
#    username: foo
#    password: bar
#    from: drone@your-domain.com
#+   attachment: build-result.xml
#    when:
#      status: [ changed, failure ]